common/models/Category.php
<?php

namespace common\models;

use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * @property int $id
 * @property string $name
 * @property int $sort_order
 * @property int $status
 *
 * @property Room[] $rooms
 */
class Category extends ActiveRecord
{
    public static function tableName(): string
    {
        return '{{%category}}';
    }

    public function rules(): array
    {
        return [
            ['name', 'string', 'min' => 2, 'max' => 255],
            ['name', 'unique'],

            ['sort_order', 'integer'],
            ['sort_order', 'default', 'value' => null],

            ['status', 'integer'],
            ['status', 'in', 'range' => Status::getStatusList()],
            ['status', 'default', 'value' => 0]
        ];
    }

    public function attributeLabels(): array
    {
        return [
            'id' => 'ID',
            'name' => 'Категория',
            'status' => 'Статус'
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getRooms(): ActiveQuery
    {
        return $this->hasMany(Room::class, ['category_id' => 'id']);
    }
}

frontend/models/Category.php
<?php

namespace frontend\models;

use common\models\Room;
use common\models\Status;
use yii\db\ActiveQuery;

class Category extends \common\models\Category
{
    /**
     * @return ActiveQuery
     */
    public function getRooms(): ActiveQuery
    {
        return $this->hasMany(Room::class, ['category_id' => 'id'])
            ->andWhere([
                'room.status' => Status::ACTIVE,
                'room.is_available' => true
            ]);
    }
}

frontend/controllers/BookingController.php
<?php

namespace frontend\controllers;

use common\services\BookingService;
use frontend\models\Booking;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class BookingController extends Controller
{
    public function __construct(
        $id, $module,
        private BookingService $bookingService
    )
    {
        parent::__construct($id, $module);
    }

    public function actionCreate(int $id): Response|string
    {
        $model = new Booking([
            'room_id' => $id
        ]);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();

            return $this->redirect(['/booking/view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model
        ]);
    }

    /**
     * @throws NotFoundHttpException
     */
    public function actionView(int $id): string
    {
        $booking = $this->bookingService->getBooking($id, ['room', 'room.category']);

        return $this->render('view', [
            'booking' => $booking
        ]);
    }
}

frontend/controllers/CategoryController.php
<?php

namespace frontend\controllers;

use frontend\models\Category;
use common\models\Status;
use common\services\CategoryService;
use frontend\models\search\CategorySearch;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class CategoryController extends Controller
{
    public function __construct(
        $id, $module,
        private CategoryService $categoryService
    )
    {
        parent::__construct($id, $module);
    }

//    public function actionIndex(): string
//    {
//        $categoryList = Category::find()
//            ->with('rooms')
//            ->where(['status' => Status::ACTIVE])
//            ->orderBy('sort_order')
//            ->all();
//
//        return $this->render('index', [
//            'categoryList' => $categoryList
//        ]);
//    }

    public function actionIndex(): string
    {
        $searchModel = new CategorySearch();
        $dataProvider = $searchModel
            ->search(Yii::$app->request->get())
            ->query
            ->all();

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * @throws NotFoundHttpException
     */
    public function actionView(int $id): string
    {
        $category = $this->categoryService->getCategory($id, 'rooms');

        return $this->render('view', [
            'category' => $category
        ]);
    }
}

frontend/views/category/index.php
<?php

/* @var $this yii\web\View */
/* @var $dataProvider Category[] */
/* @var $searchModel CategorySearch */

use frontend\models\Category;
use frontend\models\search\CategorySearch;
use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\helpers\Url;

$this->title = 'Список категорий';
?>

<div class="site-index">
    <div class="jumbotron text-center bg-transparent">
        <h1 class="display-4"><?= $this->title ?></h1>
    </div>

    <div class="body-content">
        <div class="row">
            <div class="post-search">
                <?php $form = ActiveForm::begin([
                    'action' => ['index'],
                    'method' => 'get',
                    'enableClientValidation'=>false
                ]); ?>

                <?= $form->field($searchModel, 'name') ?>

                <div class="form-group">
                    <?= Html::submitButton('Искать', ['class' => 'btn btn-primary']) ?>
                    <?= Html::a('Сбросить', Url::to(['/category/index']) , ['class' => 'btn btn-default']) ?>
                </div>

                <?php ActiveForm::end(); ?>
            </div>
        </div>
        <div class="row">

            <?php foreach ($dataProvider as $category): ?>
                <div class="col-lg-4">
                    <h2><?= $category->name ?></h2>
                    <h5>Свободных номеров (<?= count($category->rooms) ?? 0 ?>)</h5>
                    <p>
                        <a href="<?= Url::to(['category/view', 'id' => $category->id]) ?>" class="btn btn-outline-secondary">
                            Смотреть категорию "<?= $category->name ?>"
                        </a>
                    </p>
                </div>
            <?php endforeach; ?>

        </div>
    </div>
</div>

frontend/views/category/view.php
<?php

/* @var $this yii\web\View */
/* @var $category Category */

use frontend\models\Category;
use yii\helpers\Url;

$this->title = "Категория $category->name"
?>

<div class="site-index">
    <div class="jumbotron text-center bg-transparent">
        <h1 class="display-4"><?= $this->title ?></h1>
    </div>
    <div class="body-content">
        <div class="row">

            <?php foreach ($category->rooms as $room): ?>
                <div class="col-lg-4">
                    <h2>Комната <?= $room->number ?></h2>
                    <p>
                        <a href="<?= Url::to(['booking/create', 'id' => $room->id]) ?>" class="btn btn-outline-secondary">
                            Забронировать комнату "<?= $room->number ?>"
                        </a>
                    </p>
                </div>
            <?php endforeach; ?>

        </div>
    </div>
</div>